package com.example.platformerp.enums;

public enum Permissions {
    STUDENT_CREATE,
    STUDENT_GET,
    STUDENT_DELETE,
    STUDENT_UPDATE,
    ADMIN_CREATE,
    ADMIN_GET_ALL,
    ADMIN_BLOCK,
    ADMIN_DELETE,
    MANAGER_CREATE,
    MANAGER_BLOCK,
    MANAGER_DELETE,
    MANAGER_GET,
    GROUP_CREATE,
    GROUP_GET,
    TEACHER_CREATE,
    TEACHER_GET,
    DO_TASK,
    SUBJECT_CREATE,
    SUBJECT_GET,
    SUBJECT_DELETE,
    GROUP_UPDATE, SUBJECT_UPDATE

}
